# Depois de me configurar, renomeie este arquivo para Config.ini e preencha os caminhos e informações necessárias para o ambiente de produção. Certifique-se de que os caminhos estejam corretos e que as credenciais do banco de dados estejam atualizadas.

# Caminhos das pastas teste
[ambiente]
ambiente=Prod

[Prod]
# Sim para que os logs sejam gerados, Não para que não sejam gerados
log=Sim
# Caminho onde os arquivos tratados serão salvos
cam_destino=
# Caminho onde está a análise diária de disponibilidade
cam_analise=
# Caminho onde está o arquivo de volumetria zero de transações
cam_zero=
# Caminho onde está o arquivo de expurgo de componentes
cam_componentes=
# Caminho secundário onde os arquivos para tratativa está estão salvos
cam_tratar=
# Caminho onde estão salvos os arquivos para tratativas
cam_pasta_raiz=
# Caminho onde está salvo o arquivo de transações
cam_transacao=
# Caminho onde está salvo o arquivo de autorizações
cam_autorizacoes=
# Caminho onde os arquivos originais para backup serão salvos
cam_backup=
# Caminho onde os arquivos de consumo de nata estão disponíveis
cam_consumo_nata=
# Caminho onde o diário de bordo está salvo
cam_diario=
# Caminho onde o arquivo de controle de execução está salvo
cam_json=
# Quantidade de dias para filtrar os arquivos de volumetria zero
dias_filtro_zero=
# Quantidade de dias para filtrar os arquivos de análise diária de disponibilidade
dias_filtro_ana=
# Quantidade de dias para filtrar os arquivos de expurgo de componentes
dias_filtro_comp=
# BANCO
# Usuário do banco de dados
USER=
# Senha do banco de dados
PASSWORD=
# DNS do banco de dados
DNS=
# Porta do banco de dados
PORT=
# Serviço do banco de dados
SERVICE=
# Caminho onde o Oracle Client está instalado
ORACLE_HOME=
# Caminho onde o banco de dados SQLite está salvo
banco_dados=